### PR TITLE
Feature/missingness joe

### PR DESCRIPTION
**Pull request by joebrew**
@mbrudd A minor PR with some suggestions (to be accepted and merged; rejected; or commented on) by you (pertaining to your open PR).

### CODE REVIEW

**Comment by joebrew** [comment]
@mbrudd Please review. The purpose of this PR is loop through each country for the missingness report (and to make one not have to knit manually)

**Comment by mbrudd** [comment]
I'm planning to hold off on this PR until I've finished the country-by-country report generation. I think that some of your suggested changes (looping through countries to create reports) will be incorporated after the work on `create_report_rmd.R` is done; that script creates the Rmd file that we'll then process with rmarkdown::render to create the PDFs.

**Comment by joebrew** [comment]
@mbrudd Is this now ready to merge?

**Comment by mbrudd** [comment]
Not yet. Most of `report.Rmd` is ready to go, but I'm working through the artisanal bits one question at a time. If you knit the current version of `report.Rmd` in the repo, you'll see what I mean in, e.g., questions 26, 28c, 41b, ... Those should all be taken care of by EOD.

**Pull request closed without merging**
